/** Table names required by CINEYOU_MASTER_SPEC Sections CG–CN. */
export const REQUIRED_TABLES = [
  "user",
  "session",
  "account",
  "verification",
  "profiles",
  "workspaces",
  "workspace_members",
  "workspace_invitations",
  "businesses",
  "brand_assets",
  "presenter_identities",
  "identity_assets",
  "assets",
  "projects",
  "project_references",
  "creative_versions",
  "production_jobs",
  "production_events",
  "generation_attempts",
  "credit_wallets",
  "credit_transactions",
  "plans",
  "subscriptions",
  "payments",
  "payment_events",
  "notifications",
  "support_tickets",
  "consents",
  "audit_logs",
  "app_settings",
  "prompt_framework_versions",
  "rate_limit_events",
] as const;
